version: "3"

services:
  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - ./api/:/app
    ports:
      - "9000:5000"

  ui:
    build: ./ui
    container_name: ui
    restart: always
    ports:
      - "8085:8000"
    volumes:
      - ./ui/:/app